### ISSUE TITLE
Control Panel API :: Rocket Status

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#105]
## Blocked by
- [ ] #104

## Task
Look at the lines here
https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/c23e462b7de2a08840f1880a0bbc4391bbe3b1c4/SOAR_Echo_Base/Controllers/control_panel.py#L68-L73

We labeled these `sender functions` because their job is to relay to the frontend the specific data that the frontend needs, currently they don't do much, however based on our [UI Deisng](https://github.com/usfsoar/NSL_23-24_PayloadEECS/wiki/2%E2%80%902%E2%80%902024-%E2%80%90-UI-Design-For-Control-Panel), there are some new functions we want to create  to send data. For now we will focus on the ***rocket status***, that is the data that will go to the box in our UI design labeled *Rocket Altitude*. We will need to:

- [ ] Add a new sender function called `update_drone_status`
- [ ] The function shall use 1 parameter:  *barometer_data*(BAROMETER object)
- [ ] At the end the function shall emit an event `update_drone_status` using `socketio` and send a json that includes the 1 paramter

## Guided solution
Feel free to use this guided solution or to come up with your own approach:

1. Below the existing sender functions on [SOAR_Echo_Base/controllers/control_panel.py](https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/c23e462b7de2a08840f1880a0bbc4391bbe3b1c4/SOAR_Echo_Base/Controllers/control_panel.py) add a new sender function called:
```python
def update_rocket_status(barometer_data=None):
```
2. Add a conditional so that if the barometer_data is None, then immediately return it was probably a fluke in our telemetry.
3. Then similar to the other functions call `socketio.emit`. This function takes 2 paramters, the first is the name of the event to emit which is **update_rocket_status** and second is the data to send, which as we said we want it to be a json object like this:
```python
{'barometer': barometer_data}
```
4. Given that for now this function isn't being called from anywhere in particular, test if your syntax is correct by running the server. Refer to the [readme under SOAR_Echo_Base](https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/main/SOAR_Echo_Base/Readme.md) on how to run this.
