### ISSUE TITLE
🚁 Connect the LUX H7 Flight Controller to the current drone ESCs

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#57]
Connect the Luminer flight controller to the current drone ESC. See if it can control the motors or not

## Tasks
- [x] Connect the motors to the Lux H7 flight controller
- [x] Research how to power the whole system from a single battery
- [x] Power the whole system and test if the Lux H7 can move the motors

## Blocked by
- [x] #64
