### ISSUE TITLE
Streamline Deployment State Machine Logic

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#80]
Currently our state machine logic for the deployment module works, but is somewhat messy:
https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/d5bc982b022a50b2701f1b62085fb768d9bbcbfa/deploy_module/deploy_module_backup/deploy_module_backup.ino#L231-L271

## Tasks
- [x] Create a branch and call it `issues/80-state machine logic` and checkout to it
- [x] Streamline the logic to use less variables or speed up the process
- [x] Make pull request to bring your changes to the main branch

## Important
Whatever logic you create make sure that:
- it can be stopped via`Stop` function of the deployment class
- if `Retract` function of the deployment class is called the Deployment check immediately skips to the retract portion
- The `GetState` function from the deployment class can get the current state of the state machine

## Reference
Here is a reference to the state machine we are aiming for:
```mermaid
stateDiagram-v2
[*] --> IDLE
IDLE --> IDLE
IDLE--> FORWARD : Triggered
FORWARD --> FORWARD
FORWARD --> WAIT : 20 seconds have passed
WAIT --> WAIT
WAIT --> RETRACT : 10 seconds have passed
RETRACT --> RETRACT
RETRACT --> COMPLETE : 20 seconds have passed
COMPLETE --> [*]
```
