### ISSUE TITLE
IMU Custom class :: Setup function

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#81]
Inside of [TestingDev/sensor_classes/](https://github.com/usfsoar/NSL_23-24_PayloadEECS/tree/main/testing_dev/sensor_classes) there is a header file called `soar_imu.h` and an implementation file called `soar_imu.cpp`.

## Tasks
- [ ] Create a function in this SOAR_IMU class to setup the BNO055 sensor
- [ ] Make sure to get the i2c pin numbers in the class constructor
- [ ] Test it by calling it on `sensor_classes.ino`

> ***NOTE*** the purpose of this custom class is to contain as much code as possible in the class itself to not clutter anything outside, therefore when testing in `sensor_classes.ino` make sure you only create an object for the class and call the class Setup function on Arduino's `void setup()`
> Reference to [this](https://learn.adafruit.com/adafruit-bno055-absolute-orientation-sensor/overview)
