### ISSUE TITLE
IMU Custom Class :: Read Acceleration Vector

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#82]
Inside of [TestingDev/sensor_classes/](https://github.com/usfsoar/NSL_23-24_PayloadEECS/tree/main/testing_dev/sensor_classes) there is a header file called `soar_imu.h` and an implementation file called `soar_imu.cpp`.

## Tasks
- [ ] Create a function in this SOAR_IMU class to read only the linear acceleration vector and return an array of `float`
- [ ] Make sure if we fail to read you can call the setup class from this function to try and reset the BNO055
- [ ] Test it by calling it on `sensor_classes.ino`, compiling it and running it on an Arduino Hooked up to a BNO055

> ***NOTE*** the purpose of this custom class is to contain as much code as possible in the class itself to not clutter anything outside, therefore when testing in `sensor_classes.ino` make sure you only create an object for the class and call the class Setup function on Arduino's `void setup()`

## Blocked by:
- [x] #81
