### ISSUE TITLE
BAROMETER Custom Class :: Setup function

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#83]
Inside of [TestingDev/sensor_classes/](https://github.com/usfsoar/NSL_23-24_PayloadEECS/tree/main/testing_dev/sensor_classes) there is a header file called `soar_barometer.h` and an implementation file called `soar_barometer.cpp`.

## Tasks
- [ ] Create a function in this SOAR_IMU class to setup the BMP390 sensor
- [ ] Make sure to get the i2c pin numbers in the class constructor
- [ ] Test it by calling it on `sensor_classes.ino`, compiling and running it on an arduino hooked up to a BMP390 sensor

> Refer to the code in [deployment module](https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/f0c374179b034773fa24b0314eb4c3a8855058c6/deploy_module/deploy_module_backup/deploy_module_backup.ino#L45-L63)

## Guided solution
Feel free to follow this steps or come up with your own approach:
- In C++ to generate a separate class file, you have to define it in both a *header file* like `soar_baromter.h` and an *implementation file* like `soar_barometer.cpp`. The header file is where you would define a function inside the class, but leave it without any content. The implementation file is where you would define the class
- In `soar_bromter.h` add the following at the very begining of the file:
```
#include <Wire.h>
#include <Adafruit_Sensor.h>
#include "Adafruit_BMP3XX.h"

#define SEALEVELPRESSURE_HPA (1013.25)
```

- In the `soar_barometer.h` add the following under `private:`
```
Adafruit_BMP3XX bmp;
```
- In the `soar_baromter.h` add the following line  under  `public:`
```
void BAROMETER_SETUP();
```
- Next up in `soar_barometer.cpp` add the following lines anywhere in the file:
```
void BAROMETER_CLASS::BAROMETER_SETUP(){
}
```
- Next up refer to the code in [deployment module](https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/f0c374179b034773fa24b0314eb4c3a8855058c6/deploy_module/deploy_module_backup/deploy_module_backup.ino#L45-L63) and put the same functionality inside the BAROMETER_SETUP() function you just started on `soar_barometer.h`
- Finally any instance of `bmp` change it to: `this->bmp`
- To test it, go to `sensor_classes.ino` and at the very top add:
```
#include "soar_barometer.h
```
- Then before the setup and the loop create an object of your class
```
SOAR_BAROMETER bmpSensor;
```
- Finally in the `setup()` call the method you just created like this:
```
bmpSensor.BAROMETER_SETUP();
```
- Check you code by uploading it to the Arduino IDE, follow the setup tutorial in the [adafruit documentation](https://learn.adafruit.com/adafruit-bmp388-bmp390-bmp3xx/arduino) to get the necessary libraries installed and how to connect the BMP sensor to an Arduino UNO.
