### ISSUE TITLE
BAROMETER Custom Class :: Read Altitude Function

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#84]
Inside of [TestingDev/sensor_classes/](https://github.com/usfsoar/NSL_23-24_PayloadEECS/tree/main/testing_dev/sensor_classes) there is a header file called `soar_barometer.h` and an implementation file called `soar_barometer.cpp`.

## Tasks
- [ ] Create a function in this SOAR_BAROMETER class to read the altitude value from the BMP390 sensor, it should return only a fFL
- [ ] Make sure if the function fails to read you can call the setup class from this function to try reset it
- [ ] Test it by calling it on `sensor_classes.ino`, compiling and running it on an arduino hooked up to a BMP390 sensor

> ***NOTE*** the purpose of this custom class is to contain as much code as possible in the class itself to not clutter anything outside, therefore when testing in `sensor_classes.ino` make sure you only create an object for the class and call the class Setup function on Arduino's `void setup()`
> I suggest to copy the altimeter code in [deployment module](https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/f0c374179b034773fa24b0314eb4c3a8855058c6/deploy_module/deploy_module_backup/deploy_module_backup.ino#L65-L82)

## Blocked by
- [x] #83
