### ISSUE TITLE
DC Motor Class :: Basic Functionality

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#99]
We need to convert the following code to setup a DC motor into it's own class that can be imported to other codes. Look at this code:

https://github.com/usfsoar/NSL_23-24_PayloadEECS/blob/a73e5a1ebfe189aaa146a056c51cd2b94c98b879/testing_dev/dc-motor-test/dc-motor-test.ino#L1-L25

### Tasks:
- [ ] Create a `DC_SETUP` function that will run the code on the setup of the code snippet above
- [ ] Create a `DC_MOVE` function that will make the DC motor like in the code snippet above
- [ ] Create a `DC_STOP` function that will completely *stop* the DC motor

**Comment by CodingIndeed** [comment]
Done, the new files are under "NSL_23-24_PayloadEECS/testing_dev/dc-motor-test".
